dashboard_data = {
    "salarioLiquido": 5000,
    "totalDespesas": 2650,
    "disponivelDividas": 1350,
    "totalDividas": 28450,
    "diasRestantes": 17,
    "saudeFinanceira": 85,

    "rendimentos": [
        {"id": 1, "mes": "2026-05", "fonte": "Salário Principal", "orcamentado": 5000, "recebido": 5000},
        {"id": 2, "mes": "2026-05", "fonte": "Trabalho Extra / Freelance", "orcamentado": 0, "recebido": 0},
        {"id": 3, "mes": "2026-05", "fonte": "Investimentos", "orcamentado": 0, "recebido": 0},
        {"id": 4, "mes": "2026-05", "fonte": "Outros Rendimentos", "orcamentado": 0, "recebido": 0},
    ],

    "despesas": [
        {"id": 1, "mes": "2026-05", "categoria": "Habitação", "orcamentado": 950, "realizado": 950, "percentagem": "19%"},
        {"id": 2, "mes": "2026-05", "categoria": "Transportes", "orcamentado": 400, "realizado": 400, "percentagem": "8%"},
        {"id": 3, "mes": "2026-05", "categoria": "Alimentação", "orcamentado": 600, "realizado": 600, "percentagem": "12%"},
        {"id": 4, "mes": "2026-05", "categoria": "Saúde", "orcamentado": 200, "realizado": 200, "percentagem": "4%"},
        {"id": 5, "mes": "2026-05", "categoria": "Lazer", "orcamentado": 200, "realizado": 200, "percentagem": "4%"},
        {"id": 6, "mes": "2026-05", "categoria": "Outros", "orcamentado": 300, "realizado": 300, "percentagem": "6%"},
    ],

    "dividas": [
        {
            "id": 1,
            "mesInicio": "2026-05",
            "credor": "Cartão de Crédito",
            "saldoInicial": 5000,
            "saldo": 5000,
            "prestacaoMensal": 500,
            "tipoJuros": "mensal",
            "taxaJuros": 8.0,
            "progresso": 80,
            "prioridade": "Alta",
            "status": "ativa",
        },
        {
            "id": 2,
            "mesInicio": "2026-05",
            "credor": "Empréstimo Pessoal",
            "saldoInicial": 10000,
            "saldo": 10000,
            "prestacaoMensal": 450,
            "tipoJuros": "anual",
            "taxaJuros": 3.5,
            "progresso": 65,
            "prioridade": "Alta",
            "status": "ativa",
        },
        {
            "id": 3,
            "mesInicio": "2026-05",
            "credor": "Financiamento Auto",
            "saldoInicial": 8000,
            "saldo": 8000,
            "prestacaoMensal": 300,
            "tipoJuros": "anual",
            "taxaJuros": 1.5,
            "progresso": 40,
            "prioridade": "Média",
            "status": "ativa",
        },
        {
            "id": 4,
            "mesInicio": "2026-05",
            "credor": "Crédito Loja",
            "saldoInicial": 1450,
            "saldo": 1450,
            "prestacaoMensal": 100,
            "tipoJuros": "mensal",
            "taxaJuros": 2.9,
            "progresso": 15,
            "prioridade": "Baixa",
            "status": "ativa",
        },
    ],

    "pagamentosDividas": [],

    "objetivos": [
        {"id": 1, "mes": "2026-05", "nome": "Fundo de Emergência", "objetivo": 3000, "atual": 2100, "percentagem": 70},
        {"id": 2, "mes": "2026-05", "nome": "Quitar Cartão de Crédito", "objetivo": 5000, "atual": 1000, "percentagem": 20},
        {"id": 3, "mes": "2026-05", "nome": "Entrada para Casa", "objetivo": 15000, "atual": 3750, "percentagem": 25},
        {"id": 4, "mes": "2026-05", "nome": "Nova Viatura", "objetivo": 20000, "atual": 6000, "percentagem": 30},
    ],

    "pagamentos": [
        {"id": 1, "mes": "2026-05", "data": "01/06", "nome": "Habitação", "valor": 700, "dias": "2 dias"},
        {"id": 2, "mes": "2026-05", "data": "05/06", "nome": "Cartão de Crédito", "valor": 500, "dias": "5 dias"},
        {"id": 3, "mes": "2026-05", "data": "07/06", "nome": "Luz", "valor": 85, "dias": "7 dias"},
        {"id": 4, "mes": "2026-05", "data": "12/06", "nome": "Internet", "valor": 35, "dias": "12 dias"},
    ],
}
